version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ops/docker/web/Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - ollama

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - web

  ollama:
    build:
      context: .
      dockerfile: ops/docker/ollama/Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  static_volume:
  ollama_data: